### ISSUE TITLE
how to resolve `AttributeError: 'Config' object has no attribute 'all_kwargs'`?

### ISSUE THREAD

**Issue by KimmiShi** [apple/ml-cross-entropy#13]
Hi, I am trying to run `ml-cross-entropy/benchmark`, but I encountered the following error:
···
Traceback (most recent call last):
  File "/work/ml-cross-entropy/benchmark/__main__.py", line 15, in <module>
    from cut_cross_entropy import linear_cross_entropy
  File "/work/ml-cross-entropy/cut_cross_entropy/__init__.py", line 2, in <module>
    from cut_cross_entropy.linear_cross_entropy import (
  File "/work/ml-cross-entropy/cut_cross_entropy/linear_cross_entropy.py", line 20, in <module>
    from cut_cross_entropy.cce import cce_linear_cross_entropy
  File "/work/ml-cross-entropy/cut_cross_entropy/cce.py", line 7, in <module>
    from cut_cross_entropy.cce_backward import cce_backward_kernel
  File "/work/ml-cross-entropy/cut_cross_entropy/cce_backward.py", line 237, in <module>
    _cce_backward_kernel = cce_backward_autotune()(_cce_backward_kernel)  # type: ignore
  File "/work/ml-cross-entropy/cut_cross_entropy/tl_autotune.py", line 422, in cce_backward_autotune
    return _heuristics_from_config(_cce_backward_best_config())
  File "/work/ml-cross-entropy/cut_cross_entropy/tl_autotune.py", line 368, in _heuristics_from_config
    return triton.heuristics({k: (lambda args, _v=v: _v) for k, v in config.all_kwargs().items()})
AttributeError: 'Config' object has no attribute 'all_kwargs'
···

my env info:
```
Python 3.10.4
torch: 2.4.0+cu118
triton: 3.0.0
GPU: A800
```

**Comment by KimmiShi** [comment]
triton version should be higher than 3.0.0, I don't know the minimal version that could work, I tried 3.1.0 and it works.

perhaps the triton version requirement in readme needs update.
